/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PS05366;

/**
 *
 * @author NNQ Hanie
 */
import java.awt.*;


import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Genn
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form GDchinh
     */
    public main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    
    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url = "jdbc:sqlserver://localhost:1433;databaseName=QuanLyDT;user=sa;password=123";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel(){
            ImageIcon icon=new ImageIcon("nen.jpg");
            public void paintComponent(Graphics g){
                Dimension d=getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }};
            lb1 = new javax.swing.JLabel();
            lbtime = new javax.swing.JLabel();
            jMenuBar1 = new javax.swing.JMenuBar();
            jMenu1 = new javax.swing.JMenu();
            Itemuser = new javax.swing.JMenuItem();
            Itempass = new javax.swing.JMenuItem();
            Itemexit = new javax.swing.JMenuItem();
            jMenu2 = new javax.swing.JMenu();
            Itemsv = new javax.swing.JMenuItem();
            Itemdiem = new javax.swing.JMenuItem();
            jMenu6 = new javax.swing.JMenu();
            jMenuItem1 = new javax.swing.JMenuItem();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("FPT Polytechnic");
            setResizable(false);
            setSize(new java.awt.Dimension(700, 500));
            addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
                }
            });

            jPanel2.setPreferredSize(new java.awt.Dimension(700, 500));

            lb1.setForeground(new java.awt.Color(51, 51, 255));

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 595, Short.MAX_VALUE)
                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(202, 202, 202)
                    .addComponent(lbtime, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)
                    .addComponent(lbtime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 370, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
            jMenuBar1.setAutoscrolls(true);
            jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuBar1.setMinimumSize(new java.awt.Dimension(56, 35));
            jMenuBar1.setPreferredSize(new java.awt.Dimension(161, 42));

            jMenu1.setBackground(new java.awt.Color(255, 255, 255));
            jMenu1.setForeground(new java.awt.Color(0, 0, 51));
            jMenu1.setText(" System");
            jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jMenu1.setPreferredSize(new java.awt.Dimension(60, 19));

            Itemuser.setForeground(new java.awt.Color(0, 0, 51));
            Itemuser.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\user.png")); // NOI18N
            Itemuser.setText("User Management");
            Itemuser.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ItemuserActionPerformed(evt);
                }
            });
            jMenu1.add(Itemuser);

            Itempass.setForeground(new java.awt.Color(0, 0, 51));
            Itempass.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\key.png")); // NOI18N
            Itempass.setText("Change Password");
            Itempass.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ItempassActionPerformed(evt);
                }
            });
            jMenu1.add(Itempass);

            Itemexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
            Itemexit.setForeground(new java.awt.Color(0, 0, 51));
            Itemexit.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\exit.png")); // NOI18N
            Itemexit.setText("Exit");
            Itemexit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ItemexitActionPerformed(evt);
                }
            });
            jMenu1.add(Itemexit);

            jMenuBar1.add(jMenu1);

            jMenu2.setForeground(new java.awt.Color(0, 0, 51));
            jMenu2.setText("Manager");
            jMenu2.setPreferredSize(new java.awt.Dimension(60, 19));

            Itemsv.setForeground(new java.awt.Color(0, 0, 51));
            Itemsv.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\sv.png")); // NOI18N
            Itemsv.setText("Student  Management");
            Itemsv.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ItemsvActionPerformed(evt);
                }
            });
            jMenu2.add(Itemsv);

            Itemdiem.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\a-mark.png")); // NOI18N
            Itemdiem.setText("Point management");
            Itemdiem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ItemdiemActionPerformed(evt);
                }
            });
            jMenu2.add(Itemdiem);

            jMenuBar1.add(jMenu2);

            jMenu6.setForeground(new java.awt.Color(0, 0, 51));
            jMenu6.setText("    Help");
            jMenu6.setPreferredSize(new java.awt.Dimension(60, 19));

            jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\about.png")); // NOI18N
            jMenuItem1.setText("About");
            jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem1ActionPerformed(evt);
                }
            });
            jMenu6.add(jMenuItem1);

            jMenuBar1.add(jMenu6);
            jMenu6.getAccessibleContext().setAccessibleName("  Trợ giúp");

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void ItemexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ItemexitActionPerformed

    private void ItempassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItempassActionPerformed
        // TODO add your handling code here:
        doipass a = new doipass();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItempassActionPerformed

    private void ItemsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsvActionPerformed
        // TODO add your handling code here:
        qlsinhvien a=null;
        try {
            a = new qlsinhvien();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }

        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemsvActionPerformed

    private void ItemuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemuserActionPerformed
        qluser a=null;
        try {
            a = new qluser();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }

        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemuserActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (quyen.quyen1.equalsIgnoreCase("Admin")){
        } else if (quyen.quyen1.equalsIgnoreCase("Lecturers")) {
            Itemsv.setEnabled(false);
            Itemuser.setEnabled(false);
        } else if (quyen.quyen1.equalsIgnoreCase("Staff")) {
            Itemuser.setEnabled(false);
            Itemdiem.setEnabled(false);
        }

    }//GEN-LAST:event_formWindowOpened

    private void ItemdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemdiemActionPerformed
        // TODO add your handling code here:
     qldiem a=null;
        
        try {
            a = new qldiem();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemdiemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       JOptionPane.showMessageDialog(this, "Assignment SOF203"
                               + "\nPerform :              Như NNQ"
                               + "\nSupport :               Vũ LNH -- Anh NX "
                               + "\nInstructor :         HuongTT"
                               + "\nLicense :               NhunnqPS05366", "Notify", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Itemdiem;
    private javax.swing.JMenuItem Itemexit;
    private javax.swing.JMenuItem Itempass;
    private javax.swing.JMenuItem Itemsv;
    private javax.swing.JMenuItem Itemuser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lbtime;
    // End of variables declaration//GEN-END:variables
}
