/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PS05366;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author NNQ Hanie
 */
public class qlsinhvien extends javax.swing.JFrame {

    public qlsinhvien() throws ClassNotFoundException, SQLException, SQLException {
        initComponents();
        hienthi();
        setLocationRelativeTo(null);
    }
    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url = "jdbc:sqlserver://localhost:1433;databaseName=QuanLyDT;user=sa;password=123";

    public ArrayList<Sinhvien> sinhvienlist() throws ClassNotFoundException, SQLException {
        ArrayList<Sinhvien> ds = new ArrayList<>();
        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url);
            String query = "select * from SinhVien";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Sinhvien sinhvien = null;
            while (rs.next()) {
                sinhvien = new Sinhvien(rs.getString("MaSV"), rs.getString("TenSV"), rs.getString("NgaySinh"), rs.getString("Lop"), rs.getFloat("diemjava"), rs.getFloat("diemsql"), rs.getFloat("diemav"), rs.getFloat("diemtb"));
                ds.add(sinhvien);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return ds;
    }

    public void hienthi() throws ClassNotFoundException, SQLException {
        ArrayList<Sinhvien> list = sinhvienlist();
        DefaultTableModel md = (DefaultTableModel) tbds.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getmasv();
            row[1] = list.get(i).gettensv();
            row[2] = list.get(i).getngaysinh();
            row[3] = list.get(i).getlop();
            md.addRow(row);
        }
    }

    public void status(String query, String message) throws SQLException {
        try {
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            if ((st.executeUpdate(query)) == 1) {
                DefaultTableModel md = (DefaultTableModel) tbds.getModel();
                md.setRowCount(0);
                hienthi();
                JOptionPane.showMessageDialog(null, "Already " + message);
            } else {
                JOptionPane.showMessageDialog(null, "Error " + message);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        btnew = new javax.swing.JButton();
        btadd = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        btfind = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtclass = new javax.swing.JTextField();
        txtma = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbds = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        txtfind = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Itemhome = new javax.swing.JMenuItem();
        Itemuser = new javax.swing.JMenuItem();
        Itempass = new javax.swing.JMenuItem();
        Itemexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Itemdiem = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student  Management");
        setBackground(new java.awt.Color(36, 47, 65));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        btnew.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\new-file (2).png")); // NOI18N
        btnew.setText("New");
        btnew.setFocusable(false);
        btnew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnew.setPreferredSize(new java.awt.Dimension(60, 60));
        btnew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnew);

        btadd.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\add.png")); // NOI18N
        btadd.setText("Add");
        btadd.setFocusable(false);
        btadd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btadd.setPreferredSize(new java.awt.Dimension(60, 60));
        btadd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });
        jToolBar1.add(btadd);

        btedit.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\edit.png")); // NOI18N
        btedit.setText("Update");
        btedit.setFocusable(false);
        btedit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btedit.setPreferredSize(new java.awt.Dimension(60, 60));
        btedit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });
        jToolBar1.add(btedit);

        btdelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\xoa.png")); // NOI18N
        btdelete.setText("Delete");
        btdelete.setFocusable(false);
        btdelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btdelete.setPreferredSize(new java.awt.Dimension(60, 60));
        btdelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(btdelete);

        btfind.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\find.png")); // NOI18N
        btfind.setText("Find");
        btfind.setFocusable(false);
        btfind.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btfind.setPreferredSize(new java.awt.Dimension(60, 60));
        btfind.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfindActionPerformed(evt);
            }
        });
        jToolBar1.add(btfind);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Student code :");

        txtdate.setBackground(new java.awt.Color(36, 47, 65));
        txtdate.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        txtdate.setForeground(new java.awt.Color(255, 255, 255));
        txtdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdate.setBorder(null);

        txtname.setBackground(new java.awt.Color(36, 47, 65));
        txtname.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 255, 255));
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Student name:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Birth of date  : ");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Class             :");

        txtclass.setBackground(new java.awt.Color(36, 47, 65));
        txtclass.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        txtclass.setForeground(new java.awt.Color(255, 255, 255));
        txtclass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtclass.setBorder(null);

        txtma.setBackground(new java.awt.Color(36, 47, 65));
        txtma.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        txtma.setForeground(new java.awt.Color(255, 255, 255));
        txtma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtma.setBorder(null);
        txtma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student  Management");

        tbds.setBackground(new java.awt.Color(240, 240, 240));
        tbds.setForeground(new java.awt.Color(36, 47, 65));
        tbds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student code", "Student name", "Birth of date", "Class"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbds);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(43, 43, 43)
                                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtclass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtclass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtfind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtfind.setForeground(new java.awt.Color(51, 102, 255));
        txtfind.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfind.setText("Enter the student code to find");
        txtfind.setBorder(null);
        txtfind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtfindMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtfind)
                .addGap(0, 0, 0))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(56, 24));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(161, 35));

        jMenu1.setForeground(new java.awt.Color(0, 0, 51));
        jMenu1.setText("   System");
        jMenu1.setPreferredSize(new java.awt.Dimension(60, 19));
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Itemhome.setForeground(new java.awt.Color(0, 0, 51));
        Itemhome.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\home.png")); // NOI18N
        Itemhome.setText("Home page");
        Itemhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemhomeActionPerformed(evt);
            }
        });
        jMenu1.add(Itemhome);

        Itemuser.setForeground(new java.awt.Color(0, 0, 51));
        Itemuser.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\user.png")); // NOI18N
        Itemuser.setText("User Management");
        Itemuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemuserActionPerformed(evt);
            }
        });
        jMenu1.add(Itemuser);

        Itempass.setForeground(new java.awt.Color(0, 0, 51));
        Itempass.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\key.png")); // NOI18N
        Itempass.setText("Change Password");
        Itempass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItempassActionPerformed(evt);
            }
        });
        jMenu1.add(Itempass);

        Itemexit.setForeground(new java.awt.Color(0, 0, 51));
        Itemexit.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\exit.png")); // NOI18N
        Itemexit.setText("Exit");
        Itemexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemexitActionPerformed(evt);
            }
        });
        jMenu1.add(Itemexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 51));
        jMenu2.setText(" Manager");
        jMenu2.setPreferredSize(new java.awt.Dimension(60, 19));

        Itemdiem.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\a-mark.png")); // NOI18N
        Itemdiem.setText("Point management");
        Itemdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemdiemActionPerformed(evt);
            }
        });
        jMenu2.add(Itemdiem);

        jMenuBar1.add(jMenu2);

        jMenu6.setForeground(new java.awt.Color(0, 0, 51));
        jMenu6.setText("     Help");
        jMenu6.setPreferredSize(new java.awt.Dimension(60, 19));

        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\about.png")); // NOI18N
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ItemhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemhomeActionPerformed
        main a = new main();
        a.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_ItemhomeActionPerformed

    private void ItempassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItempassActionPerformed
        // TODO add your handling code here:\
        try {
            doipass a = new doipass();
            a.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
    }//GEN-LAST:event_ItempassActionPerformed

    private void ItemexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ItemexitActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // TODO add your handling code here:
        
            try {
                String query = "update SinhVien set TenSV='" + txtname.getText() + "',NgaySinh='" + txtdate.getText() + "',Lop='" + txtclass.getText() + "' where MaSV='" + txtma.getText() + "'";
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(this, "You want to fix?", "Notify", dialogButton);
                if (dialogResult == 0) {
                    status(query, "Edit students");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error " + ex);
            }
        
    }//GEN-LAST:event_bteditActionPerformed

    private void txtmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaActionPerformed

    private void txtfindMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfindMouseReleased
        // TODO add your handling code here:
        txtfind.setText("");
    }//GEN-LAST:event_txtfindMouseReleased

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        // TODO add your handling code here:
        if (batloi() == 0) {
            try {
                Connection con = DriverManager.getConnection(url);
                String sql = "select * from SinhVien where MaSV = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, txtma.getText());
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "This student already exists");
                } else {
                    String query = "insert into SinhVien (MaSV,TenSV,NgaySinh,Lop) values ('" + txtma.getText() + "',N'" + txtname.getText() + "','" + txtdate.getText() + "',N'" + txtclass.getText() + "')";
                    status(query, "Add new students");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error " + ex);
            }
        }
    }//GEN-LAST:event_btaddActionPerformed

    private void btnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewActionPerformed
        // TODO add your handling code here:
        txtma.setText("");
        txtname.setText("");
        txtdate.setText("");
        txtclass.setText("");
        txtfind.setText("");

        JOptionPane.showMessageDialog(this, "Enter information");
    }//GEN-LAST:event_btnewActionPerformed

    private void tbdsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdsMouseClicked
        // TODO add your handling code here:
        int i = tbds.getSelectedRow();
        TableModel md = tbds.getModel();
        txtma.setText(md.getValueAt(i, 0).toString());
        txtname.setText(md.getValueAt(i, 1).toString());
        txtdate.setText(md.getValueAt(i, 2).toString());
        txtclass.setText(md.getValueAt(i, 3).toString());
    }//GEN-LAST:event_tbdsMouseClicked

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
        try {
            String query = "delete from SinhVien where MaSV='" + txtma.getText() + "'";
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Want to delete?", "Notify", dialogButton);
            if (dialogResult == 0) {
                status(query, "Delete students");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex);
        }
    }//GEN-LAST:event_btdeleteActionPerformed

    private void btfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfindActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = DriverManager.getConnection(url);
            String sql = "select * from SinhVien where MaSV = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtfind.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String a = rs.getString("MaSV");
                String b = rs.getString("TenSV");
                String c = rs.getString("NgaySinh");
                String d = rs.getString("Lop");
                JOptionPane.showMessageDialog(this, "Had found", "Notify", 1);
                for (int i = 0; i < sinhvienlist().size(); i++) {
                    txtma.setText(a);
                    txtname.setText(b);
                    txtdate.setText(c);
                    txtclass.setText(d);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Not found", "Notify", 1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btfindActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (quyen.quyen1.equalsIgnoreCase("admin")) {
            Itemdiem.setEnabled(true);
            Itemuser.setEnabled(true);
        } else if (quyen.quyen1.equalsIgnoreCase("giang vien")) {
            Itemuser.setEnabled(false);
            Itemdiem.setEnabled(true);
        } else if (quyen.quyen1.equalsIgnoreCase("can bo")) {
            Itemdiem.setEnabled(false);
            Itemuser.setEnabled(false);
        }

    }//GEN-LAST:event_formWindowOpened

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        tbds.setEnabled(false);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void ItemuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemuserActionPerformed
        qluser a = null;
        try {
            a = new qluser();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(qlsinhvien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(qlsinhvien.class.getName()).log(Level.SEVERE, null, ex);
        }

        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemuserActionPerformed

    private void ItemdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemdiemActionPerformed
        try {
            qldiem a = new qldiem();
            a.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
        
    }//GEN-LAST:event_ItemdiemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, "Assignment SOF203"
            + "\nPerform :              Như NNQ"
            + "\nSupport :               Vũ LNH -- Anh NX "
            + "\nInstructor :         HuongTT"
            + "\nLicense :               NhunnqPS05366", "Notify", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
   public int batloi() {
        if(txtma.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a student code");
            txtma.requestFocus();
        }else if (txtma.getText().matches("^PS[0-9]{5}$") == false) {
            JOptionPane.showMessageDialog(this, "Import in PSxxxxx format");
            txtma.requestFocus();
        } else if(txtname.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a name");
            txtname.requestFocus();
        }else if (txtname.getText().matches("^[a-zA-Z \\àáạãăắằặẵâấầẫẳặêềếệễôỏỗộốồơởỡớờịĩíìuúùụũủưửữừứựđÀÁẠÃĂẮẰẶẴÂẤẦẪẲẶÊẾỀỆỄÔỎỖỘỐỒƠỞỠỚỜỊĨÍÌUÚÙỤŨỦƯỬỮỪỨỰĐ]{2,30}$") == false) {
            JOptionPane.showMessageDialog(this, "Greater than 2 characters, include(a-z)+(A-Z)");
            txtname.requestFocus();
        } else if(txtdate.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a date of birth");
            txtdate.requestFocus();
        } else if (txtdate.getText().matches("^[0-9]{1,2}/[0-9]{1,2}/[0-9]{2,4}$") ==false) {
            JOptionPane.showMessageDialog(this, "mm/dd/yyyy");
            txtdate.requestFocus();
        } else if(txtclass.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a class");
            txtclass.requestFocus();
        } else if (txtclass.getText().matches("^PT[0-9]{5}$") ==false) {
            JOptionPane.showMessageDialog(this, "Import in PTxxxxx format");
            txtclass.requestFocus();
        } else {
            return 0;
        }
        return 1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(qlsinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(qlsinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(qlsinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(qlsinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new qlsinhvien().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(qlsinhvien.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(qlsinhvien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Itemdiem;
    private javax.swing.JMenuItem Itemexit;
    private javax.swing.JMenuItem Itemhome;
    private javax.swing.JMenuItem Itempass;
    private javax.swing.JMenuItem Itemuser;
    private javax.swing.JButton btadd;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btedit;
    private javax.swing.JButton btfind;
    private javax.swing.JButton btnew;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbds;
    private javax.swing.JTextField txtclass;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtfind;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables

}
