/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PS05366;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author NNQ Hanie
 */
public class qluser extends javax.swing.JFrame {

    public qluser() throws ClassNotFoundException, SQLException, SQLException {
        initComponents();
        hienthi();
        setLocationRelativeTo(null);
    }
    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url = "jdbc:sqlserver://localhost:1433;databaseName=QuanLyDT;user=sa;password=123";

    public ArrayList<Users> userlist() throws ClassNotFoundException, SQLException {
        ArrayList<Users> ds = new ArrayList<>();
        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url);
            String query = "select * from Users";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Users users = null;
            while (rs.next()) {
                users = new Users(rs.getInt("mauser"), rs.getString("ten"), rs.getString("username"), rs.getString("password"), rs.getString("quyen"));
                ds.add(users);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return ds;
    }

    public void hienthi() throws ClassNotFoundException, SQLException {
        ArrayList<Users> list = userlist();
        DefaultTableModel md = (DefaultTableModel) tbds.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getMauser();
            row[1] = list.get(i).getTen();
            row[2] = list.get(i).getQuyen();
            row[3] = list.get(i).getUser();
            row[4] = list.get(i).getPass();
            md.addRow(row);
        }

    }

    public void status(String query, String message) throws SQLException {
        try {
            Connection con = DriverManager.getConnection(url);
            Statement st = con.createStatement();
            if ((st.executeUpdate(query)) == 1) {
                DefaultTableModel md = (DefaultTableModel) tbds.getModel();
                md.setRowCount(0);
                hienthi();
                JOptionPane.showMessageDialog(null, "Already " + message);
            } else {
                JOptionPane.showMessageDialog(null, "Error " + message);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        btnew = new javax.swing.JButton();
        btadd = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        btdelete = new javax.swing.JButton();
        btfind = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbds = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        cbChucvu = new javax.swing.JComboBox<>();
        txtma = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        txtfind = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Itemhome = new javax.swing.JMenuItem();
        Itempass = new javax.swing.JMenuItem();
        Itemexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Itemsv = new javax.swing.JMenuItem();
        Itemdiem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Management");
        setBackground(new java.awt.Color(36, 47, 65));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        btnew.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\new-file (2).png")); // NOI18N
        btnew.setText("New");
        btnew.setFocusable(false);
        btnew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnew.setPreferredSize(new java.awt.Dimension(60, 60));
        btnew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnew);

        btadd.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\add.png")); // NOI18N
        btadd.setText("Add");
        btadd.setFocusable(false);
        btadd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btadd.setPreferredSize(new java.awt.Dimension(60, 60));
        btadd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });
        jToolBar1.add(btadd);

        btedit.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\edit.png")); // NOI18N
        btedit.setText("Update");
        btedit.setFocusable(false);
        btedit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btedit.setPreferredSize(new java.awt.Dimension(60, 60));
        btedit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });
        jToolBar1.add(btedit);

        btdelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\xoa.png")); // NOI18N
        btdelete.setText("Delete");
        btdelete.setFocusable(false);
        btdelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btdelete.setPreferredSize(new java.awt.Dimension(60, 60));
        btdelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(btdelete);

        btfind.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\find.png")); // NOI18N
        btfind.setText("Find");
        btfind.setFocusable(false);
        btfind.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btfind.setPreferredSize(new java.awt.Dimension(60, 60));
        btfind.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfindActionPerformed(evt);
            }
        });
        jToolBar1.add(btfind);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Name       :");

        txtuser.setBackground(new java.awt.Color(36, 47, 65));
        txtuser.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        txtuser.setForeground(new java.awt.Color(255, 255, 255));
        txtuser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtuser.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Position :");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Username       :");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Password        :");

        txtpass.setBackground(new java.awt.Color(36, 47, 65));
        txtpass.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        txtpass.setForeground(new java.awt.Color(255, 255, 255));
        txtpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpass.setBorder(null);

        txtname.setBackground(new java.awt.Color(36, 47, 65));
        txtname.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 255, 255));
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.setBorder(null);
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Management");

        tbds.setBackground(new java.awt.Color(240, 240, 240));
        tbds.setForeground(new java.awt.Color(36, 47, 65));
        tbds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User code", "Name", "Position", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbds);

        cbChucvu.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        cbChucvu.setForeground(new java.awt.Color(51, 102, 255));
        cbChucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--", "Administrator", "Lecturers", "Staff" }));

        txtma.setBackground(new java.awt.Color(36, 47, 65));
        txtma.setFont(new java.awt.Font("Goudy Stout", 3, 12)); // NOI18N
        txtma.setForeground(new java.awt.Color(255, 255, 255));
        txtma.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtma.setBorder(null);
        txtma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtma, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(43, 43, 43)
                                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtfind.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtfind.setForeground(new java.awt.Color(51, 102, 255));
        txtfind.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfind.setText("Enter the Username to find");
        txtfind.setBorder(null);
        txtfind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtfindMouseReleased(evt);
            }
        });
        txtfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtfind)
                .addGap(0, 0, 0))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(56, 24));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(161, 35));

        jMenu1.setForeground(new java.awt.Color(0, 0, 51));
        jMenu1.setText("   System");
        jMenu1.setPreferredSize(new java.awt.Dimension(60, 19));
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Itemhome.setForeground(new java.awt.Color(0, 0, 51));
        Itemhome.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\home.png")); // NOI18N
        Itemhome.setText("Home page");
        Itemhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemhomeActionPerformed(evt);
            }
        });
        jMenu1.add(Itemhome);

        Itempass.setForeground(new java.awt.Color(0, 0, 51));
        Itempass.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\key.png")); // NOI18N
        Itempass.setText("Change Password");
        Itempass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItempassActionPerformed(evt);
            }
        });
        jMenu1.add(Itempass);

        Itemexit.setForeground(new java.awt.Color(0, 0, 51));
        Itemexit.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\exit.png")); // NOI18N
        Itemexit.setText("Exit");
        Itemexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemexitActionPerformed(evt);
            }
        });
        jMenu1.add(Itemexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 51));
        jMenu2.setText(" Manager");
        jMenu2.setPreferredSize(new java.awt.Dimension(60, 19));

        Itemsv.setForeground(new java.awt.Color(0, 0, 51));
        Itemsv.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\sv.png")); // NOI18N
        Itemsv.setText("Student  Management");
        Itemsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsvActionPerformed(evt);
            }
        });
        jMenu2.add(Itemsv);

        Itemdiem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\a-mark.png")); // NOI18N
        Itemdiem1.setText("Point management");
        Itemdiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Itemdiem1ActionPerformed(evt);
            }
        });
        jMenu2.add(Itemdiem1);

        jMenuBar1.add(jMenu2);

        jMenu6.setForeground(new java.awt.Color(0, 0, 51));
        jMenu6.setText("    Help");
        jMenu6.setPreferredSize(new java.awt.Dimension(60, 19));

        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\NNQ Hanie\\Desktop\\ASM2_PS05366\\about.png")); // NOI18N
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ItemhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemhomeActionPerformed
        main a = new main();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemhomeActionPerformed

    private void ItempassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItempassActionPerformed
        // TODO add your handling code here:\
        try {
            doipass a = new doipass();
            a.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
    }//GEN-LAST:event_ItempassActionPerformed

    private void ItemexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ItemexitActionPerformed

    private void ItemsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsvActionPerformed
        // TODO add your handling code here:
        try {
            qlsinhvien a = new qlsinhvien();
            a.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
    }//GEN-LAST:event_ItemsvActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // TODO add your handling code here:
        if (batloi() == 0) {
            try {
                String query = "update Users set Ten='" + txtname.getText() + "',Username='" + txtuser.getText() + "',Password='" + txtpass.getText() + "',Quyen='" + cbChucvu.getSelectedItem() + "' where MaUser='" + txtma.getText() + "'";
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(this, "You want to fix? ", "Notify", dialogButton);
                if (dialogResult == 0) {
                    status(query, "Edit user");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error " + ex);
            }
        }
    }//GEN-LAST:event_bteditActionPerformed

    private void txtfindMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfindMouseReleased
        // TODO add your handling code here:
        txtfind.setText("");
    }//GEN-LAST:event_txtfindMouseReleased

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        // TODO add your handling code here:
        if (batloi() == 0) {
            try {
                Connection con = DriverManager.getConnection(url);
                String sql = "select * from Users where Username = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, txtuser.getText());
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "This user already exists");
                } else {
                    String query = "insert into Users (Ten,Quyen,Username,Password) values (N'" + txtname.getText() + "','" + cbChucvu.getSelectedItem() + "','" + txtuser.getText() + "','" + txtpass.getText() + "')";
                    status(query, "Add new users");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error " + e);
            }
        }
    }//GEN-LAST:event_btaddActionPerformed

    private void btnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewActionPerformed
        // TODO add your handling code here:
        txtma.setText("");
        txtname.setText("");
        txtuser.setText("");
        txtpass.setText("");
        txtfind.setText("");

        
        btadd.setEnabled(true);
        JOptionPane.showMessageDialog(this, "Enter information");
    }//GEN-LAST:event_btnewActionPerformed

    private void btdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdeleteActionPerformed
        // TODO add your handling code here:
        try {
            String query = "delete from Users where MaUser='" + txtma.getText() + "'";
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Want to delete?", "Notify", dialogButton);
            if (dialogResult == 0) {
                status(query, "Delete user");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex);
        }
    }//GEN-LAST:event_btdeleteActionPerformed

    private void btfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfindActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = DriverManager.getConnection(url);
            String sql = "select * from Users where Username = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtfind.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String q = rs.getString("MaUser");
                String a = rs.getString("Ten");
                String b = rs.getString("Username");
                String c = rs.getString("Password");
                String d = rs.getString("Quyen");
                JOptionPane.showMessageDialog(this, "Had found", "Notify", 1);
                for (int i = 0; i < userlist().size(); i++) {
                    txtma.setText(q);
                    txtname.setText(a);
                    cbChucvu.setSelectedItem(d);
                    txtuser.setText(b);
                    txtpass.setText(c);
                }
                btadd.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Not found", "Notify", 1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btfindActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        tbds.setEnabled(false);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void Itemdiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Itemdiem1ActionPerformed
        // TODO add your handling code here:
         try {
            qldiem a = new qldiem();
            a.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }
    }//GEN-LAST:event_Itemdiem1ActionPerformed

    private void txtfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfindActionPerformed

    private void tbdsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdsMouseClicked
        // TODO add your handling code here:
        int i = tbds.getSelectedRow();
        TableModel md = tbds.getModel();
        txtname.setText(md.getValueAt(i, 1).toString());
        cbChucvu.setSelectedItem(md.getValueAt(i, 2).toString());
        txtuser.setText(md.getValueAt(i, 3).toString());
        txtpass.setText(md.getValueAt(i, 4).toString());
        txtma.setText(md.getValueAt(i, 0).toString());
    }//GEN-LAST:event_tbdsMouseClicked

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, "Assignment SOF203"
            + "\nPerform :              Như NNQ"
            + "\nSupport :               Vũ LNH -- Anh NX "
            + "\nInstructor :         HuongTT"
            + "\nLicense :               NhunnqPS05366", "Notify", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    public int batloi() {
        if (txtname.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Please enter a name");
        } else if (txtuser.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Please enter a username");
        } else if (txtpass.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Please enter a password");
        } else {
            return 0;
        }
        return 1;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(qluser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(qluser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(qluser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(qluser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new qluser().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(qluser.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(qluser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Itemdiem1;
    private javax.swing.JMenuItem Itemexit;
    private javax.swing.JMenuItem Itemhome;
    private javax.swing.JMenuItem Itempass;
    private javax.swing.JMenuItem Itemsv;
    private javax.swing.JButton btadd;
    private javax.swing.JButton btdelete;
    private javax.swing.JButton btedit;
    private javax.swing.JButton btfind;
    private javax.swing.JButton btnew;
    private javax.swing.JComboBox<String> cbChucvu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbds;
    private javax.swing.JTextField txtfind;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables

}
